### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by benhalverson** [devbinod/nodewithmongo#1]
You asked for some feedback in https://gitter.im/nodejs/node

Inconsistent spacing between {} when you import stuff and the values you imported 
for example https://github.com/devbinod/nodewithmongo/blob/master/src/app.ts#L1-L6

You have a folder called const and a file called constants but also one for dbconfig with config
I think this can all be put into one folder file called config. Here's an example of how I do it.
https://github.com/benhalverson/airbnb-clone-node-api/tree/master/config

You have quite a few unused imports 
for example `import e = require("express");`

In the findAll method you are not using req so you could do 
`findAll = async (_: Request, res: Response) => {...}`

Why do you have this file?
https://github.com/devbinod/nodewithmongo/blob/master/src/models/user.ts
Since this appears to be demoware and the model is so small why not just do this...
```
import { Document } from 'mongoose';
export interface UserModel extends Document {
	firstName: string,
	lastName: string,
	email?: string
}
```

https://github.com/devbinod/nodewithmongo/blob/master/src/services/user.service.ts
You could do this ES2015 shorthand for the id
if the key and value of the object are the same then you don't need to do { _id: id } 
{ _id } will work 

```
 async delete(_id: string): Promise<Boolean> {
    let isDelete: boolean = false; // also the boolean type is not needed here.
    await this.model.user
      .deleteOne({
        _id
      }) ...
  }
```

Hope this helps 👍

**Comment by devbinod** [comment]
Hi @benhalverson, Thanks for your feedback. I have completed your feedback. Could you verify if you have time? Happy Coding.
